### ISSUE TITLE
`jdatetime.datetime.isoformat` fails on python 2.7 when called after `from __future__ import unicode_literals`

### ISSUE THREAD

**Issue by 5j9** [slashmili/python-jalali#102]
```python
$ python2
Python 2.7.13 (default, Apr 16 2021, 14:02:03)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jdatetime
>>> jdatetime.datetime(1398, 4, 11, 11, 6, 5, 123456).isoformat('T')
u'1398-04-11T11:06:05.123456'
>>> from __future__ import unicode_literals
>>> jdatetime.datetime(1398, 4, 11, 11, 6, 5, 123456).isoformat('T')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/nfs/labstore-secondary-tools-home/5j9/venv2/local/lib/python2.7/site-packages/jdatetime/__init__.py", line 1269, in isoformat
    'argument 1 must be a single character: {}'.format(sep)
AssertionError: argument 1 must be a single character: T
>>>

```

I believe the code above should work, even after the `__future__` import; similar to the way, for example, `jdatetime.datetime(1398, 4, 11, 11, 6, 5, 123456).strftime('%Y')` works.

# Please include your runtime information

* jdatetime version: 3.7.0
* Python version: 2.7
* OS: Linux

**Comment by hramezani** [comment]
Thanks @5j9 for the patch.
Could you please add test for this patch?
